### ISSUE TITLE
Error on no indoor sensor

### ISSUE THREAD

**Issue by frankhommers** [allan-gam/interceptWH2600#1]
When no Indoor sensor was ever connected, you get the following error:

Exception happened during processing of request from ('10.0.0.167', 29619)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./interceptWH2600.py", line 100, in do_GET
    updateDomoticz(jsonQs)
  File "./interceptWH2600.py", line 128, in updateDomoticz
    updateDomoDevice(c, jsonQs)
  File "./interceptWH2600.py", line 156, in updateDomoDevice
    reportedTemp = round(temp_c(jsonQs['indoortempf']), 1)
KeyError: 'indoortempf'

**Comment by allan-gam** [comment]
Thanks.

Can you try version 1.0.1 and please report back if it works.

**Comment by frankhommers** [comment]
I connected an indoor sensor to bypass the bug. Now when I disconnect it in the UI of Weather Station, that last readings are still showing, so I don't think I am able to reproduce the same settings. 

I installed 1.0.1 anyway, and still works, but can't say for sure the bug is fixed.

**Comment by allan-gam** [comment]
OK. Thanks. Just get back again if you experience any problems.
